name: End-to-End Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # or the version required by netlify-cli

      - name: Install Netlify CLI
        run: npm install -g netlify-cli@17.21.1

      - name: Install project dependencies
        run: npm install

      - name: Start Netlify server
        run: netlify-cli serve &

      - name: Wait for Netlify server to be ready
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:8888; do
            printf '.'
            sleep 5
          done

      - name: Run Cypress tests
        run: npm run cypress:run
        env:
          CI: true
